export type BlogPost = {
  slug: string;
  title: string;
  description: string;
  date: string;
  readTime: string;
  category: string;
  featured?: boolean;
};

export const blogPosts: BlogPost[] = [
  {
    slug: "ia-monaco-etat-des-lieux-2026",
    title: "IA à Monaco : état des lieux en 2026",
    description: "Où en sont les entreprises monégasques dans leur adoption de l'IA ? Analyse sectorielle, freins identifiés et opportunités concrètes pour la Principauté.",
    date: "2026-03-20",
    readTime: "8 min",
    category: "Analyse",
    featured: true,
  },
  {
    slug: "automatiser-conformite-lcb-ft-monaco",
    title: "Automatiser la conformité LCB-FT à Monaco",
    description: "Comment l'IA transforme les processus de lutte contre le blanchiment dans les sociétés de gestion et banques privées de la Principauté.",
    date: "2026-03-15",
    readTime: "10 min",
    category: "Guide",
    featured: true,
  },
  {
    slug: "ia-gestion-patrimoine-monaco",
    title: "IA et gestion de patrimoine à Monaco",
    description: "Collecte documentaire, échéanciers, reporting SICCFIN : les cas d'usage concrets de l'IA pour les SGP et family offices monégasques.",
    date: "2026-03-10",
    readTime: "9 min",
    category: "Secteur",
  },
  {
    slug: "ia-cabinets-avocats-droit-monegasque",
    title: "IA et droit monégasque : guide pour cabinets",
    description: "Rédaction d'actes, recherche juridique, transcription d'audiences. L'IA au service des professionnels du droit à Monaco.",
    date: "2026-03-05",
    readTime: "8 min",
    category: "Secteur",
  },
  {
    slug: "creer-site-web-ia-2-semaines",
    title: "Créer un site web professionnel en 2 semaines avec l'IA",
    description: "Les outils, la méthode et les résultats. Comment l'IA permet de livrer des sites performants en une fraction du temps traditionnel.",
    date: "2026-02-28",
    readTime: "7 min",
    category: "Guide",
  },
  {
    slug: "roi-intelligence-artificielle-mesurer-gains",
    title: "ROI de l'IA : comment mesurer les gains réels",
    description: "Méthodologie concrète pour calculer le retour sur investissement de vos projets d'intelligence artificielle. Avec exemples chiffrés.",
    date: "2026-02-20",
    readTime: "9 min",
    category: "Méthodologie",
  },
  {
    slug: "kyc-augmente-ia-banque-privee",
    title: "KYC augmenté par IA : transformer la banque privée",
    description: "Due diligence accélérée, scoring de risque automatisé, détection d'anomalies. L'IA au service de la conformité bancaire à Monaco.",
    date: "2026-02-15",
    readTime: "8 min",
    category: "Secteur",
  },
  {
    slug: "former-equipes-ia-generative",
    title: "Former ses équipes à l'IA générative : par où commencer",
    description: "Programme en 4 niveaux pour former vos équipes à l'IA générative à Monaco. Du prompt engineering aux cas d'usage métier avancés pour entreprises monégasques.",
    date: "2026-02-10",
    readTime: "7 min",
    category: "Guide",
  },
  {
    slug: "5-processus-rentables-automatiser",
    title: "Les 5 processus les plus rentables à automatiser par IA",
    description: "Gestion documentaire, conformité, facturation, reporting, correspondance. Analyse ROI de chaque levier d'automatisation.",
    date: "2026-02-05",
    readTime: "8 min",
    category: "Analyse",
  },
  {
    slug: "immobilier-luxe-ia-monaco",
    title: "L'immobilier de luxe à Monaco à l'ère de l'IA",
    description: "Matching acheteurs-biens, brochures automatisées, veille urbanistique. Comment l'IA redéfinit la promotion immobilière dans la Principauté.",
    date: "2026-01-30",
    readTime: "7 min",
    category: "Secteur",
  },
  {
    slug: "extended-monaco-programme-digital-principaute",
    title: "Extended Monaco : le programme digital de la Principauté",
    description: "Le programme Extended Monaco, lancé par le Gouvernement, pose les bases de la digitalisation. Où en est-on en 2026 et quelles opportunités pour les entreprises ?",
    date: "2026-03-28",
    readTime: "9 min",
    category: "Analyse",
    featured: true,
  },
  {
    slug: "chatgpt-claude-entreprise-monaco-quel-llm-choisir",
    title: "ChatGPT, Claude, Mistral : quel LLM pour Monaco ?",
    description: "Comparaison objective des grands modèles de langage pour un usage professionnel. Confidentialité, performance, coût et cas d'usage monégasques.",
    date: "2026-03-27",
    readTime: "10 min",
    category: "Guide",
    featured: true,
  },
  {
    slug: "rgpd-donnees-personnelles-ia-monaco",
    title: "RGPD et IA à Monaco : loi n°1.565 et conformité",
    description: "La nouvelle loi monégasque sur la protection des données impose des règles précises pour l'utilisation de l'IA. Guide de conformité complet.",
    date: "2026-03-26",
    readTime: "8 min",
    category: "Guide",
  },
  {
    slug: "family-office-monaco-digitalisation-ia",
    title: "Family offices à Monaco : digitalisation par l'IA",
    description: "Reporting, collecte documentaire, conformité, relation client. Comment les family offices monégasques utilisent l'IA pour servir mieux avec moins.",
    date: "2026-03-25",
    readTime: "11 min",
    category: "Secteur",
  },
  {
    slug: "ia-generative-monaco-opportunites-risques",
    title: "IA générative à Monaco : opportunités et risques",
    description: "ChatGPT, Midjourney, Claude dans le contexte monégasque. Ce que les dirigeants doivent savoir avant de déployer l'IA générative dans leur entreprise.",
    date: "2026-03-24",
    readTime: "9 min",
    category: "Analyse",
  },
  {
    slug: "automatiser-facturation-comptabilite-monaco",
    title: "Automatiser facturation et comptabilité à Monaco",
    description: "OCR, rapprochement automatique, contrôle TVA, génération de factures. Guide pratique pour les entreprises de la Principauté.",
    date: "2026-03-23",
    readTime: "8 min",
    category: "Guide",
  },
  {
    slug: "agent-ia-autonome-entreprise-monaco",
    title: "Agents IA autonomes : révolution pour Monaco",
    description: "Les agents IA ne se contentent plus de répondre aux questions. Ils exécutent des tâches complètes. Ce que ça change pour Monaco.",
    date: "2026-03-22",
    readTime: "9 min",
    category: "Analyse",
  },
  {
    slug: "monaco-hub-ia-europe-pourquoi",
    title: "Monaco peut-il devenir un hub IA en Europe ?",
    description: "Taille, fiscalité, talent, réglementation. Analyse des forces et faiblesses de la Principauté dans la course à l'intelligence artificielle.",
    date: "2026-03-21",
    readTime: "10 min",
    category: "Analyse",
  },
];
